// <auto-generated />
namespace TelegramBotApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _040118 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_040118));
        
        string IMigrationMetadata.Id
        {
            get { return "201810041451262_04.01.18"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
